- hosts: all
  gather_facts: no
- import_playbook: playbooks/ansible-setup.yml
- import_playbook: playbooks/development.yml
- import_playbook: playbooks/acl.yml
- import_playbook: playbooks/git.yml
- import_playbook: playbooks/python-devel.yml
- import_playbook: playbooks/stack-user.yml
- import_playbook: playbooks/projects.yml
- import_playbook: playbooks/openvswitch.yml
- import_playbook: playbooks/reboot.yml
- import_playbook: playbooks/opendaylight.yml
- import_playbook: playbooks/devstack.yml
- import_playbook: playbooks/openstack-scripts-tasks.yml
