---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install dependencies if redhat
    raw: dnf install -y python python-dnf
    become: yes
    become_user: root
    ignore_errors: yes
  - name: Install dependencies if debian
    raw: apt update && apt install -y python python-apt
    become: yes
    become_user: root
    ignore_errors: yes
  - name: setup
    setup:
  - name: Install python-selinux
    package:
      name: libselinux-python
      state: latest
    when: ansible_os_family == "RedHat"
    become: yes
    become_user: root
  - name: Install python-selinux
    package:
      name: python-selinux
      state: latest
    when: ansible_os_family == "Debian"
    become: yes
    become_user: root
  - name: Setup vagrant permissions
    lineinfile: dest=/etc/sudoers.d/vagrant line="vagrant ALL=(ALL) NOPASSWD:ALL" state=present create=yes
    become: yes
    become_user: root
