---
- hosts: all
  gather_facts: no
  tasks:
  - name: setup
    setup:
  - name: Install python
    package:
      name: python
      state: latest
    become: yes
    become_user: root
  - name: Install python-dnf
    package:
      name: python-dnf
      state: latest
    become: yes
    become_user: root
    when: ansible_os_family == "RedHat"
  - name: Install python-apt
    package:
      name: python-apt
      state: latest
    become: yes
    become_user: root
    when: ansible_os_family == "Debian"
  - name: setup
    setup:
  - name: Install python-selinux
    package:
      name: libselinux-python
      state: latest
    when: ansible_os_family == "RedHat"
    become: yes
    become_user: root
  - name: Install python-selinux
    package:
      name: python-selinux
      state: latest
    when: ansible_os_family == "Debian"
    become: yes
    become_user: root
  - name: Setup vagrant permissions
    lineinfile: dest=/etc/sudoers.d/vagrant line="vagrant ALL=(ALL) NOPASSWD:ALL" state=present create=yes
    become: yes
    become_user: root
