---
- hosts: all
  tasks:
  - name: Update system packages
    package: name=* state=latest
    become: yes
    become_user: root
  - name: Install C Development Tools and Libraries (RedHat)
    dnf: name="@C Development Tools and Libraries"
    register: development_installed
    when: ansible_os_family == "RedHat"
    become: yes
    become_user: root
  - name: Install C Development Tools and Libraries (Debian)
    apt: name=build-essential
    register: development_installed
    when: ansible_os_family == "Debian"
    become: yes
    become_user: root
  - name: Install kernel development dependencies
    package: name=kernel-devel
    register: kernel_devel_installed
    become: yes
    become_user: root
  - name: Install xauth
    package: name=xauth
    become: yes
    become_user: root
  - name: Install tigervnc
    package: name=tigervnc
    become: yes
    become_user: root
  - name: Install and update libnghttp2
    package: name=libnghttp2
    become: yes
    become_user: root
  - name: Update vim-minimal
    package: name=vim-minimal state=latest
    become: yes
    become_user: root
  - name: Install vim
    package: name=vim
    become: yes
    become_user: root
  - name: Install gpg
    package: name=gpg
    become: yes
    become_user: root
