---
- hosts: all
  tasks:
  - name: Clone devstack
    git:
      dest=/home/stack/devstack
      repo=https://github.com/openstack-dev/devstack
      version={{ devstack_version | d("HEAD", True) }}
    become: yes
    become_user: stack
    tags:
    - devstack-only
  - name: Install local.conf
    template: src={{ local_conf_file }} dest=/home/stack/devstack/local.conf
    become: yes
    become_user: stack
    tags:
    - devstack-only
  - name: Run devstack
    shell: |
      tmux start-server
      tmux new-session -d -s stack -n stack
      tmux send-keys -t stack:stack "cd /home/stack/devstack" C-m
      tmux send-keys -t stack:stack "./stack.sh" C-m
    become: yes
    become_user: stack
    tags:
    - devstack-only
