---
- hosts: all
  tasks:
  - name: Install python-pip
    package: name=python-pip state=present
    register: pip_installed
    become: yes
    become_user: root
  - name: Upgrade pip
    pip: name=pip state=latest
    become: yes
    become_user: root
  - name: Upgrade tox
    pip: name=tox state=latest
    become: yes
    become_user: root
