---
- hosts: all
  tasks:
  - name: Check if restart is needed in Debian
    block:
      - name: Check if restart is needed in Debian
        stat:
          path: /var/run/reboot-required
        register: reboot_required
      - set_fact: reboot_required={{reboot_required.stat.exists}}
    when: ansible_os_family == "Debian"
  - name: Check if restart is needed in RedHat 
    block:
      - name: Install yum-utils
        package: name=yum-utils
      - name: Check if restart is needed in RedHat
        shell: needs-restarting -r
        register: reboot_required
      - set_fact: reboot_required={{reboot_required.rc!=0}}
    when: ansible_os_family == "RedHat"
  - name: Reboot server
    block:
      - name: Restart server
        shell: sleep 2 && shutdown -r now "Ansible updates triggered"
        async: 1
        poll: 0
        ignore_errors: true
        become: yes
        become_user: root
      - name: waiting for server to come back
        wait_for:
          port: 22
          host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
          delay: 10
        connection: local
    when: reboot_required == True
